
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular-app
spec:
  selector:
    matchLabels:
      app: my-angular-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: my-angular-app
    spec:
      containers:
      - name: my-angular-app
        image: my-angular-app
        ports:
        - containerPort: 80